# Generated by Django 5.2 on 2025-09-18 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_delete_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
